language: python
python:
- '3.7'
install:
- make compile
jobs:
  include:
    - stage: test
      script: 
        - make travis-test
    - stage: package
      script:
        - make package
    - stage: publish
      script:
        - make publish
      if: branch = master
    - stage: docker image
      script:
        - make image
      if: branch = master
    - stage: docker imagePush
      script:
        - make imagePush
      if: branch = master


branches:
  except:
  - /^v\d+\.\d+\.\d+$/
env:
  matrix:
    secure: PPNujFlfNOFdgKfbvQ+0k5dYDf7jJTUETObu5eTV4BkCKpZgVDHFKz+OmApIS+DrqzX9F8tPkF/h0KkN5UClcZQViygfTxLQqAOp0hRL42rU76aw3UWER4i45aRsYNkpgHTb+apLDuGcNuxnOC8O2jnRiqG3E6mFDxhny+BwFZv9iTsgwnXOv310Ns+pHztZGK8ZPfYZD4GWfrKgyVrLu+EVmSQx78lSdaFYauX1DzJaPVrpdz13YhFWfWseYiBzMzx+TX3GZiIitdU7YEQk2pCw1rmr0rS+toEBh/YcTgzYBeJwscLBAS5wk63/Fi9WtUYu9fiFF35yP97KJ43E+56sQCuG+JdZruhoSvt5Hb816OQo48mbQYPWz9NVgif6Pz94mTWsTaAdnxf806V0k6OYimenfAz6EYTYRP+oQPHaFLNzrgglM3rQwsgHZ0P6OzofgKqjjp57VL+dejhiCnpoD4Co7ntck4jOzGncD2r7Udk5FPu8dgifJwSrYELUFsMIO84srdtTw/N9YI185uzuk+qnAYPFwcCRl8qtuk9qQ98qn7lcTVxpM3+XFvPGUTdkb2L75SChtafgPxNb3GIEhVs7TpL2OLaO3/8EW6uMSDAGvBGRZuXDqqHeA/qDNZB2nzdfMczjlk/ffRK461Jz+ieBIWYpOCuUjFrsJBc=
